#!/bin/bash
SECONDS=0
# --------------------------------
if [ -z "$WHEREAMI" ]; then
    pushd .. > /dev/null
    export WHEREAMI=$PWD
    popd > /dev/null
fi
# --------------------------------
export JAVA_HOME=$(/usr/libexec/java_home -v1.8)
export ANT_HOME=$WHEREAMI/ant
export PATH=$PATH:$ANT_HOME/bin
export TOMCAT_HOME=$WHEREAMI/tomcat
export WEBAPPS=$TOMCAT_HOME/webapps
export JAVA_OPTS=
export CATALINA_OPTS="-Doracle.jdbc.autoCommitSpecCompliant=false"
echo -----------------------------
say "go test"
case "$1" in
	'-?'|'-help'|'--help')
		echo "usage: goT"
		echo "       test tox"
		echo -----------------------------
		;;
	*)
# 		osascript -e 'quit app "Firefox64"'
# 		osascript -e 'quit app "Google Chrome"'
# 		osascript -e 'quit app "Safari"'
		ant load.test
		if [ $? = 0 ] ; then
			echo -----------------------------
			ant clean
			echo -----------------------------
			"$TOMCAT_HOME/bin/shutdown.sh"
			rm -fr "$WEBAPPS/test*"
			echo -----------------------------
			cp -v test.war "$WEBAPPS"
			"$TOMCAT_HOME/bin/startup.sh"
			echo -----------------------------
			say "success"
			echo -----------------------------
# 			unitTest
			echo -----------------------------
# 			open -a Firefox64 'http://localhost:8080/test/element/toxElement3.html'
# 			open -a Safari 'http://localhost:8080/test/element/toxElement3.html'
# 			open -a 'Google Chrome' 'http://localhost:8080/test/element/toxElement3.html'
			echo -----------------------------
			say "complete"
		else
			say "fail"
		fi
		;;
esac
duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."