#!/bin/bash
echo -----------------------------
time curl -X GET  -u tester:testerpass "http://localhost:8080/tox/example/alive" > test1.html
open -a Firefox test1.html
# time curl -X GET  -u tester:testerpass "http://localhost:8080/restful/scott/departmentByNo?deptNo=10"
# time curl -X GET  -u tester:testerpass "http://localhost:8080/restful/scott/departmentByName?dname=SALES"
# time curl -X GET  -u tester:testerpass "http://localhost:8080/restful/scott/departmentByLoc?loc=BOSTON"
echo -----------------------------


# what about dept by no and name... i.e. multiple params?

# what about put and post, what is the payload?